"""empty message

Revision ID: 4490c4e09c56
Revises: a2dc6cba336c
Create Date: 2019-06-22 13:58:45.287362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4490c4e09c56'
down_revision = 'a2dc6cba336c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('room_data_id', postgresql.UUID(), nullable=False))
    op.create_foreign_key(None, 'projects', 'data', ['room_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'room_data_id')
    # ### end Alembic commands ###
